run:
  name: "3T_Final_16_Channels"
  seed: 42
  gpu: 2

data:
  base_dir: "../../data/3T/B0corrected_wo_LipidMask"

  train_subjects:
    # ClimaX_Brisbane
    - "ClimaX_Brisbane/Vol4/Res36x36"
    - "ClimaX_Brisbane/Vol4/Res50x50"
    - "ClimaX_Brisbane/Vol5/Res36x36"
    - "ClimaX_Brisbane/Vol5/Res50x50"
    - "ClimaX_Brisbane/Vol6/Res36x36"
    - "ClimaX_Brisbane/Vol6/Res50x50"
    - "ClimaX_Brisbane/Vol7/Res36x36"
    - "ClimaX_Brisbane/Vol7/Res50x50"

    # PRISMAFIT_Vienna
    - "PRISMAFIT_Vienna/Vol01_BS/Res36x36"
    - "PRISMAFIT_Vienna/Vol01_BS/Res50x50"
    - "PRISMAFIT_Vienna/Vol01_BS/Res64x64x41"
    - "PRISMAFIT_Vienna/Vol02_LH/Res36x36"
    - "PRISMAFIT_Vienna/Vol02_LH/Res50x50"
    - "PRISMAFIT_Vienna/Vol02_LH/Res64x64x41"
    - "PRISMAFIT_Vienna/Vol02_SM_RESCAN/Res36x36"
    - "PRISMAFIT_Vienna/Vol02_SM_RESCAN/Res50x50"
    - "PRISMAFIT_Vienna/Vol02_SM_RESCAN/Res64x64x41"
    - "PRISMAFIT_Vienna/Vol03_WB/Res36x36"
    - "PRISMAFIT_Vienna/Vol03_WB/Res50x50"
    - "PRISMAFIT_Vienna/Vol03_WB/Res64x64x41"

    # PRISMA_Vienna
    - "PRISMA_Vienna/Vol01_WB/Res36x36"
    - "PRISMA_Vienna/Vol01_WB/Res50x50"
    - "PRISMA_Vienna/Vol01_WB/Res64x64x41"
    - "PRISMA_Vienna/Vol01_WB/Res64x64x47"
    - "PRISMA_Vienna/Vol02_BS/Res36x36"
    - "PRISMA_Vienna/Vol02_BS/Res50x50"
    - "PRISMA_Vienna/Vol02_BS/Res64x64x41"
    - "PRISMA_Vienna/Vol02_BS/Res64x64x47"
    - "PRISMA_Vienna/Vol03_SH/Res36x36"
    - "PRISMA_Vienna/Vol03_SH/Res50x50"
    - "PRISMA_Vienna/Vol03_SH/Res64x64x41"
    - "PRISMA_Vienna/Vol03_SH/Res64x64x47"
    - "PRISMA_Vienna/Vol04_SM/Res36x36"
    - "PRISMA_Vienna/Vol04_SM/Res50x50"
    - "PRISMA_Vienna/Vol04_SM/Res64x64x41"
    - "PRISMA_Vienna/Vol04_SM/Res64x64x47"

    # VIDA_Vienna
    - "VIDA_Vienna/Vol01_PW/Res36x36"
    - "VIDA_Vienna/Vol01_PW/Res50x50"
    - "VIDA_Vienna/Vol01_PW/Res64x64x41"
    - "VIDA_Vienna/Vol01_PW/Res64x64x47"
    - "VIDA_Vienna/Vol02_BS/Res36x36"
    - "VIDA_Vienna/Vol02_BS/Res50x50"
    - "VIDA_Vienna/Vol02_BS/Res64x64x41"
    - "VIDA_Vienna/Vol03_TE/Res36x36"
    - "VIDA_Vienna/Vol03_TE/Res50x50"
    - "VIDA_Vienna/Vol03_TE/Res64x64x41"
    - "VIDA_Vienna/Vol04_AA/Res36x36"
    - "VIDA_Vienna/Vol04_AA/Res50x50"
    - "VIDA_Vienna/Vol04_AA/Res64x64x41"

  val_subjects:
    # ClimaX_Brisbane
    - "ClimaX_Brisbane/Vol8/Res36x36"
    - "ClimaX_Brisbane/Vol8/Res50x50"

    # PRISMAFIT_Vienna
    - "PRISMAFIT_Vienna/Vol04_LP/Res36x36"
    - "PRISMAFIT_Vienna/Vol04_LP/Res50x50"
    - "PRISMAFIT_Vienna/Vol04_LP/Res64x64x41"

    # PRISMA_Vienna
    - "PRISMA_Vienna/Vol05_LH/Res36x36"
    - "PRISMA_Vienna/Vol05_LH/Res50x50"
    - "PRISMA_Vienna/Vol05_LH/Res64x64x41"
    - "PRISMA_Vienna/Vol05_LH/Res64x64x47"

    # VIDA_Vienna
    - "VIDA_Vienna/Vol05_LH/Res36x36"
    - "VIDA_Vienna/Vol05_LH/Res50x50"
    - "VIDA_Vienna/Vol05_LH/Res64x64x41"

  simulation_config: "../Simulation/3T_on_the_fly.yaml"

  resources:
    version: "water_lipid_v1"
    filename: "TrainData/SimulationResources_{version}.h5"

output:
  base_dir: "../../models"
  overwrite: false

training:
  batch_size: 3500
  epochs: 400

  # Number of newly simulated training batches per epoch.
  n_batches: 300

  # Print information for every individual batch.
  verbose: false

validation:
  # A fixed synthetic validation dataset is generated once at startup
  # and reused after every epoch.
  seed: 12345
  n_spectra: 35000
  batch_size: 3300

optim:
  lr: 0.0002

scheduler:
  milestones: [50, 100, 150, 200]
  gamma: 0.5

model:
  architecture: "unet"  # "unet" or "ynet"
  n_layers: 6
  n_filters: 16
  in_channels: 2
  out_channels: 2
  dropout: 0.0

checkpoint:
  # Loads only model weights from:
  # ../../models/<preload_model>/model_last.pt
  preload: false
  preload_model: ""