run:
  name: "3T_50x50_Unet_1.1_6Layer"
  seed: 42
  gpu: 1

data:
  base_dir: "../../data/3T"
  train_subjects: ['ClimaX_Brisbane/Vol4/Res50x50']
  val_subjects: ['PRISMAFIT_Vienna/Vol01_BS/Res50x50']

  simulation_config: "../Simulation/3T_on_the_fly.yaml"

  resources:
    version: "water_lipid_v1"
    filename: "TrainData/SimulationResources_{version}.h5"

output:
  base_dir: "../../models"
  overwrite: false

training:
  batch_size: 2000
  epochs: 400

  # Number of newly simulated training batches per epoch.
  n_batches: 300

  # Print information for every individual batch.
  verbose: false

validation:
  # A fixed synthetic validation dataset is generated once at startup
  # and reused after every epoch.
  seed: 12345
  n_spectra: 35000
  batch_size: 3300

optim:
  lr: 0.0008

scheduler:
  milestones: [50, 100, 150, 200, 250, 300]
  gamma: 0.5

model:
  architecture: "unet"  # "unet" or "ynet"
  n_layers: 6
  n_filters: 16
  in_channels: 2
  out_channels: 2
  dropout: 0.0

checkpoint:
  # Loads only model weights from:
  # ../../models/<preload_model>/model_last.pt
  preload: false
  preload_model: "7T_Unet_6Layer_558_NoB0Cor_2"