run:
  seed: 42

data:
  base_dir: "../data/3T"
  subjects: ['Vol01_WB/Res36x36', 'Vol02_BS/Res36x36', 'Vol03_SH/Res36x36', 'Vol04_SM/Res36x36', 'Vol05_LH/Res36x36']

  paths:
    brain_mask: "masks/brain_mask.npy"
    lipid_mask: "masks/lipid_mask.npy"
    input_data: "OriginalData/data.npy"
    output_dir: "TrainData"

water_removal:
  enabled: true
  hsvd_components: 16
  min_freq: -74
  max_freq: 74
  bandwidth: 939.85
  dwell_time: null
  parallel_jobs: 20
  slice_batch_size: 3

acquisition:
  bandwidth: 939.85
  n_timepoints: 288
  nmr_freq: 123231706.0

lipid_projection:
  target: 0.938
  tol: 5e-3
  max_iter: 60

simulation:
  n_spectra: 100000

  metabolite:
    mean_std_path: "../MetabModes/Metab_Mean_STD.txt"
    modes_glob: "../MetabModes/3T_TE0/*Exact_Modes.txt"
    min_snr: 1
    max_snr: 20
    max_freq_shift: 40
    min_peak_width: 20
    max_peak_width: 250
    max_acqu_delay: 0.002

  lipid:
    n_random_lipid: 10
    max_scaling: 70

  water:
    scaling_min: 0.1
    scaling_max: 110.0

output:
  version: "v_1.2"
  isolated_water_filename: "IsolatedWater_{version}.npy"
  train_data_filename: "TrainData_{version}.h5"
  overwrite: false