run:
  name: "7T_Ynet_Final_proj_en_1.1"
  seed: 42
  gpu: 3

data:
  base_dir: "../data/7T/B0corrected_wo_LipidMask"
  train_subjects: ['Vol3_Brisbane', 'Vol4_Brisbane', 'Vol5_Brisbane', 'Vol6_Brisbane', 'Vol2_London', 'Vol3_London', 'Vol4_London', 'Vol5_London', 'Vol6', 'Vol7', 'Vol8', 'Vol9']

  val_subjects: ['Vol5', 'Vol1_Brisbane', 'Vol1_London']

  version: "v_1.1_final"
  train_data_filename: "TrainData_{version}.h5"
  normalization: "projection_energy" # projection_energy is pauls style, max_abs does not need the lipid projection operator

output:
  base_dir: "../models"
  overwrite: false

training:
  enabled: true
  batch_size: 3500
  num_workers: 0
  epochs: 500
  n_batches: -1 # use all training batches
  n_val_batches: -1 # use all validation batches
  verbose: false

optim:
  lr: 0.00025

scheduler:
  milestones: [150, 300, 500]
  gamma: 0.25

model:
  architecture: "ynet"   # "ynet" or "unet"
  n_layers: 3
  n_filters: 8
  in_channels: 2
  out_channels: 2
  dropout: 0.0

checkpoint:
  preload: false
  preload_model: ""

prediction:
  enabled: false