run:
  name: "3T_50x50_Unet_1.0_6Layer"
  seed: 42
  gpu: 3

data:
  base_dir: "../data/3T"
  train_subjects: ['Vol01_WB/Res50x50', 'Vol02_BS/Res50x50', 'Vol03_SH/Res50x50', 'Vol04_SM/Res50x50', 'Vol05_LH/Res50x50']

  val_subjects: ['Vol01_WB/Res50x50']

  version: "v_1.0"
  train_data_filename: "TrainData_{version}.h5"
  normalization: "max_abs" # projection_energy is pauls style, max_abs does not need the lipid projection operator

output:
  base_dir: "../models"
  overwrite: false

training:
  enabled: true
  batch_size: 4000
  num_workers: 0
  epochs: 500
  n_batches: -1 # use all training batches
  n_val_batches: -1 # use all validation batches
  verbose: false

optim:
  lr: 0.00025

scheduler:
  milestones: [150, 300, 500]
  gamma: 0.25

model:
  architecture: "unet"   # "ynet" or "unet"
  n_layers: 6
  n_filters: 8
  in_channels: 2
  out_channels: 2
  dropout: 0.0

checkpoint:
  preload: false
  preload_model: ""

prediction:
  enabled: false