version: "simulation_v3"

acquisition:
  bandwidth_hz: 2778.0

  # Fixed internal and output length.
  n_timepoints: 840

  # Actually acquired FID samples before zero-filling.
  min_acquired_n_timepoints: 558
  max_acquired_n_timepoints: 840

  nmr_frequency_hz: 297222931.0


basis:
  config: "Basis_7T.yaml"


metabolites:
  config: "Metabos.yaml"

  # Sampled uniformly from
  # [-max_acquisition_delay_seconds,
  #  +max_acquisition_delay_seconds].
  max_acquisition_delay_seconds: 0.002

  # Ordinary normal distribution.
  frequency_shift:
    mean_hz: 0
    std_hz: 5

  # Normal distribution with rejection of values <= 0.
  # This is the target total Voigt FWHM.
  fwhm:
    mean_hz: 15
    std_hz: 8


noise:
  snr_min: 1.0
  snr_max: 10.0


water:
  # Normal distribution with rejection of values <= 0.
  # Directly represents:
  # max|water| / max|metabolites|
  scaling_mean: 15
  scaling_std: 25

lipids:
  n_random_fids: 10

  # Always sampled log-uniformly.
  # Directly represents:
  # max|lipids| / max|metabolites|
  scaling_min: 0.1
  scaling_max: 70.0


subject_sampling:
  mixing: "same_subject"


lipid_projection:
  enabled: false