version: "water_lipid_v1"

data:
  base_dir: "../../data/7T/NoB0Correction"

  subjects: ['Vol1_Brisbane', 'Vol3_Brisbane', 'Vol4_Brisbane', 'Vol5_Brisbane', 'Vol6_Brisbane', 'Vol1_London', 'Vol2_London', 'Vol3_London', 'Vol4_London', 'Vol5_London', 'Vol5', 'Vol6', 'Vol7', 'Vol8', 'Vol9']

  paths:
    brain_mask: "masks/brain_mask.npy"
    lipid_mask: "masks/lipid_mask.npy"
    input_data: "OriginalData/data.npy"
    output_dir: "TrainData"

water_extraction:
  bandwidth: 2778.0
  hsvd_components: 32
  min_freq: -400.0
  max_freq: 200.0
  parallel_jobs: 20
  slice_batch_size: 3

resources:
  simulation_resources_filename: "SimulationResources_{version}.h5"
  overwrite: false