version: "water_lipid_v1"

data:
  base_dir: "../../data/7T/B0corrected_wo_LipidMask"

  subjects: [
    "MS_180", 
    "MS_200", 
    "MS_210", 
    "MS_230",
    "MS_260",
    "MS_280",
    "MS_320",
    "MS_340",
    "MS_400",
    "MS_430"]

  paths:
    brain_mask: "masks/brain_mask.npy"
    lipid_mask: "masks/lipid_mask.npy"
    input_data: "OriginalData/data.npy"
    output_dir: "TrainData"

acquisition:
  bandwidth_hz: 2778.0
  nmr_frequency_hz: 297222931

water_extraction:
  hsvd_components: 32

  min_frequency_offset_ppm: -1.35 # this means upper bound 4.65 - min_frequency_offset-ppm
  max_frequency_offset_ppm: 0.51 # this means lower bound 4.65 - max_frequency_offset_ppm

  parallel_jobs: 20
  slice_batch_size: 3

resources:
  simulation_resources_filename: "SimulationResources_{version}.h5"
  overwrite: false

lipid_projection:
  enabled: true
  n_timepoints: [558]
  target: 0.938
  tol: 0.005
  max_iter: 60